name: Build and Deploy to heroku
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: npm ci

      - name: Run unit tests
        run: npm run test
        env:
          REACT_APP_NAME: ${{secrets.REACT_APP_NAME}}
          REACT_APP_TODOS_API_URL: ${{secrets.REACT_APP_TODOS_API_URL}}

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: yayis-api
          branch: main
